[package]
name = "kernel"
version = "0.0.0"
edition = "2021"

[dependencies]
bitflags = { version = "2.9.0", features = ["bytemuck"] }
bootloader_api = "0.11"
bytemuck = { version = "1.22.0", features = ["derive"] }
spin = "0.10.0"
uart_16550 = "0.3.2"
volatile = "0.6.1"
x86_64 = "0.15.2"
